# Generated by Django 5.2.4 on 2025-07-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_in2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
