# Generated by Django 5.2.4 on 2025-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check_in2", "0002_teacher_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
